---
language: python
services: docker

arch:
  - amd64
  - arm64

install:
  # Install test dependencies.
  - pip install molecule docker molecule-docker ansible ansible-lint

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/