---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: ubuntu.18.04
    image: ubuntu:18.04
  - name: ubuntu.20.04
    image: ubuntu:20.04
provisioner:
  name: ansible
verifier:
  name: testinfra